### PR TITLE
added finally block

### PR DESCRIPTION
**Pull request by mayuri2307**

### CODE REVIEW

**Comment by mayuri2307** [comment]
@arivua @jsmartfo @develemit Could you review my PR? Thank you!

**Comment by develemit** [comment]
Looks good! 🤘

**Review by develemit — APPROVED** [review]

**Review by arivua — APPROVED** [review]
Looks good. @mayuri2307 do you mind signing the CLA agreement

**Comment by mayuri2307** [comment]
@arivua @develemit apologies I was on leave. I have signed the CLA agreement. Could you please take a look at it?

**Comment by mayuri2307** [comment]
@arivua could you review it. Thank you!!

**Review by arivua — APPROVED** [review]

**Pull request merged**
